// Create an "Enum" for the collision layers
export const Layer = {
    PLAYER: 0,
    PLAYER_PROJECTILE: 1,
    PUFFER_PROJECTILE: 2,
    QUAD_BLASTER_PROJECTILE: 3,
    ASTEROID: 4,
    PUFFER: 5,
    QUAD_BLASTER: 6,
    SLICER: 7,
    SLUDGER: 8,
    SLUDGER_MINE: 9,
    HAMMERHEAD: 10,
    HAMMERHEAD_WEAPON: 11,
    INSTANT_POWERUP: 12,
    DURATION_POWERUP: 13,
    BULLET_POWERUP: 14,
    STORED_POWERUP: 15,
    PLAYER_BASE: 16,
    ENEMY_BASE: 17,
    ENEMY_BASE_PHOTON: 18
};